### ISSUE TITLE
Repo management feedback

### ISSUE THREAD

**Issue by zorrobyte** [tillkruss/Redis-Object-Cache#10]
I've been watching this project for some time now and just about every issue that has been reported or PR submitted as resulted in "I'll see if more people report this". No offense but you need to keep in mind that a vast majority of WP users haven't the slightest idea of GIT or Github and it's rather uninspiring to watch developers have their contributions snuffed - there has been some nice solutions to some issues that apply regardless of how many users "report it".

For example, I work for a company who has some pretty popular plugins who would benefit from such a Redis caching module however it's difficult to suggest this solution when I know I'll have to explain to either define a manual key salt or patch the code - for an issue I submitted a valid PR for: https://github.com/tillkruss/Redis-Object-Cache/pull/5 .

With that said and with the highest respect as a fellow dev, would it be an issue to fork this project and maintain it a different way? I know it's a permissive license however, I'm from the game dev world where devs whine constantly over someone using their work (regardless of what license) so I thought I'd ask first.

Thanks!

**Comment by tillkruss** [comment]
If you like to, I can add you to GitHub and WordPress repository.

I'm so busy with my startup that I'm trying to keep my open source work to the minimum.

**Comment by rohmann** [comment]
I have to agree that was a bit disappointing to see #9 answered like as well. I'd be open to contributing more here as well.

**Comment by tillkruss** [comment]
Or feel free to fork this plugin.

**Comment by tillkruss** [comment]
@zorrobyte I appreciate you feedback and you're welcome to fork this plugin. I originally forked this plugin too, because [the original](https://github.com/ericmann/Redis-Object-Cache) dropped support for Predis PHP library.

I did not merge your pull request #5, because your needs as a hosting provider are too specific. it doesn't make sense that every user of this plugin see unidentifiable md5 checksums as key prefixes in their Redis database. I prefer them to see easily readable strings like `foo_` or `domain_`, just like in the MySQL database.

Plus you're only having your issue, because you're using a single Redis database for multiple WordPress installations. Using a separate Redis database for each installation would solve you're problem. Or if you can't do that, you can always set a unique `WP_CACHE_KEY_SALT` for each installation.
