### ISSUE TITLE
Shared environment security

### ISSUE THREAD

**Issue by zorrobyte** [tillkruss/Redis-Object-Cache#24]
Redis is designed to only be accessed by trusted users. Some other WP Redis plugins have a NONCE_SALT variable that I assume is used for this issue.

I'd like to deploy a shared instance where multiple users will be sharing a single Redis instance. The issue is that any user can overwrite any other user's data. A malicious user could easily replace another user's cached content and for example, deface another website or cause all sorts of other issues.

Not that I'm directly asking for a solution for this plugin, but does anything at all come to mind to somehow secure Redis or provide NONCE functionality in the plugin?

**Comment by jeremyclarke** [comment]
Redis has support for multiple databases: http://www.rediscookbook.org/multiple_databases.html

There's a config option you can use to give each site it's own database. We use it to isolate our test sites into one database and all the live sites into another one. In our case we do it so we can flush the test caches without affecting the live site. 

It functions based on simple numbers (1,2,3) representing the different databases, so it would give a small amount of security since no user would know which DB was used by another user they wanted to attack.

That's not a full solution I guess but it's going to be hard for you to secure a shared Redis if your users have full control over their PHP.

Hopefully there's a solution that will add in a salt so they can only ever access your

**Comment by tillkruss** [comment]
@zorrobyte Could you provide a link that uses the `NONCE_SALT`?
